project_id = "nmcdvorpoujhbyccqjhl"

[functions.whatsapp-cloud-webhook]
verify_jwt = false

[functions.hubla-webhook]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false

[functions.custom-webhook]
verify_jwt = false

[functions.broadcast-processor]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false

[functions.d360-webhook]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false
