-- Seed de dados removido durante a migração Lovable -> Supabase próprio.
-- Estes dados vêm da origem (nnjwemmerumzkiiykpas) e serão migrados separadamente.
-- Conteúdo original preservado no histórico do Git. Ver HANDOFF-migracao-primechat.md.
